# Generated by Django 3.2.4 on 2024-04-28 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField(blank=True, default=dict, validators=[utils.validators.validate_address])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.OneToOneField(blank=True, help_text='El calendario asignado a este restaurante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='calendars.calendar')),
            ],
        ),
    ]
