# Generated by Django 3.2.4 on 2024-04-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='normal_week_schedule',
            field=models.ForeignKey(help_text='Horario normal de la semana', on_delete=django.db.models.deletion.CASCADE, related_name='normal_schedules', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='summer_week_schedule',
            field=models.ForeignKey(help_text='Horario de verano', on_delete=django.db.models.deletion.CASCADE, related_name='summer_schedules', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='winter_week_schedule',
            field=models.ForeignKey(help_text='Horario de invierno', on_delete=django.db.models.deletion.CASCADE, related_name='winter_schedules', to='schedules.schedule'),
        ),
    ]
