# Generated by Django 3.2.4 on 2024-04-23 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dish_type', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('OTHER', 'Other')], max_length=20)),
                ('ingredients', models.JSONField(default=list)),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(null=True, upload_to='dishes')),
                ('preparation_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
