# Generated by Django 3.2.4 on 2024-04-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurants',
        ),
    ]
