# Generated by Django 3.2.4 on 2024-04-16 18:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
