# Generated by Django 3.2.4 on 2024-04-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='assigned_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_tables', to='orders.order'),
        ),
    ]
