# Generated by Django 3.2.4 on 2024-04-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='finish_reserve_at',
        ),
        migrations.RemoveField(
            model_name='table',
            name='reserved_at',
        ),
    ]
