# Generated by Django 3.2.4 on 2024-04-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_assigned_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('x_position', 'y_position')},
        ),
    ]
