# Generated by Django 3.2.4 on 2024-04-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='assigned_chairs',
        ),
        migrations.RemoveField(
            model_name='table',
            name='assigned_order',
        ),
    ]
