# Generated by Django 3.2.4 on 2024-04-15 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cartcodes', '0002_alter_cartcode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
