# Generated by Django 3.2.4 on 2024-04-28 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_reserve', models.DateTimeField()),
                ('finish_reserve', models.DateTimeField()),
                ('assigned_chairs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('assigned_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='orders.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='tables.table')),
            ],
        ),
    ]
