# Generated by Django 3.2.4 on 2024-04-27 21:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Día del horario')),
                ('opened_hours', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, help_text='Lista de horas de apertura', size=None)),
                ('closed_hours', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, help_text='Lista de horas de cierre', size=None)),
                ('calendar', models.ForeignKey(help_text='El calendario asociado', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='calendars.calendar')),
            ],
        ),
    ]
