# Generated by Django 3.2.4 on 2024-04-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20240428_1748'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='calendar',
            field=models.ForeignKey(help_text='El calendario asociado', on_delete=django.db.models.deletion.CASCADE, related_name='customs_schedules', to='calendars.calendar'),
        ),
    ]
