# Generated by Django 3.2.4 on 2024-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(blank=True, help_text='Día del horario', null=True),
        ),
    ]
