# Generated by Django 3.2.4 on 2024-04-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDishLink',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_restaurants', to='dishes.dish')),
            ],
        ),
    ]
