# Generated by Django 3.2.4 on 2024-04-18 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_dish_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdishlink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
