name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to Render
        run: |
          docker-compose up -d
          sleep 1
          docker exec restaurants-web-1 bash -c "python manage.py makemigrations"
          docker exec restaurants-web-1 bash -c "python manage.py migrate"
